name: Staging Deploy

on:
  push:
    branches: [ master ]
jobs:
  

    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server:  ftp.2ndnewhawscouts.org.uk
        ftp-username: ndnewhaw
        ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
        local-dir: ./scoutmanagementapi.2ndnewhawscouts.org.uk/
